/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 MaterialSelector.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF, Text, Box } from '@react-three/drei'

export function MaterialSelector(props) {
  const { nodes, materials } = useGLTF('models/gltfjsx/MaterialSelector-transformed.glb')
  const { setSelectedObject } = props

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.MaterialSelector.geometry} material={materials['Balsa wood']} position={[1.586, 19.3, -0.774]} />
      <mesh name="Concrete" geometry={nodes.Cube.geometry} material={materials.Concrate} position={[1.586, 19.3, -0.774]} scale={[1.627, 1.243, 1.627]} onClick={(obj) => {
        obj.stopPropagation()
        setSelectedObject(obj.eventObject)
      }}>
        <group position={[0.2, 0.84, 0]} rotation={[0, 0, 0]}>
          <Box args={[0.9, 0.6, 0.02]} material-color="light-gray" position={[-0.18, 0.55, -0.1]} rotation={[0, 0, 0]}>
            <group position={[-0.41, 0.2, .02]}>
              <Text anchorX="left" color="black" fontSize={0.08} position={[0, -0.0, 0]}>Massa: 205kg</Text>
              <Text anchorX="left" color="black" fontSize={0.08} position={[0, -0.11, 0]}>Duw acceleratie: 2m/s²</Text>
              <Text anchorX="left" color="black" fontSize={0.08} position={[0, -0.3, 0]}>Wrijvingscoëfficiënts:</Text>
              <Text anchorX="left" color="black" fontSize={0.06} position={[0, -0.42, 0]}>0.193</Text>
              <Text anchorX="left" color="black" fontSize={0.06} position={[0.21, -0.42, 0]}>0.028</Text>
              <Text anchorX="left" color="black" fontSize={0.06} position={[0.43, -0.42, 0]}>0.315</Text>
              <Text anchorX="left" color="black" fontSize={0.06} position={[0.65, -0.42, 0]}>0.214</Text>
            </group>
          </Box>
        </group>
      </mesh>
      <mesh name="Ice" geometry={nodes.Cube001.geometry} material={materials['Ice.002']} position={[1.586, 19.3, -0.774]} scale={[1.627, 1.243, 1.627]} onClick={(obj) => {
        obj.stopPropagation()
        setSelectedObject(obj.eventObject)
      }} />
      <mesh name="Sand" geometry={nodes.Cube002.geometry} material={materials['Sand.001']} position={[1.586, 19.3, -0.774]} scale={[1.627, 1.243, 1.627]} onClick={(obj) => {
        obj.stopPropagation()
        setSelectedObject(obj.eventObject)
      }} />
      <mesh name="Wood" geometry={nodes.Cube003.geometry} material={materials['Wooden surface']} position={[1.586, 19.3, -0.774]} scale={[1.627, 1.243, 1.627]} onClick={(obj) => {
        obj.stopPropagation()
        setSelectedObject(obj.eventObject)
      }} />
      <mesh geometry={nodes.MaterialSelectorFrame.geometry} material={materials['Plastic Wood']} position={[1.586, 19.3, -0.774]} scale={[0.2, 0.2, 0.19]} />
    </group>
  )
}

useGLTF.preload('models/gltfjsx/MaterialSelector-transformed.glb')
