/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 Target2.glb --transform --simplify
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Target2-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Circle002.geometry} material={materials.BlackTarget} />
      <mesh geometry={nodes.Circle002_1.geometry} material={materials.RedTarget} />
    </group>
  )
}

useGLTF.preload('/Target2-transformed.glb')
