/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/CannonLevel.glb --transform --simplify
*/

import React, { forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'

export const Model = forwardRef((props, ref) => {
  const { nodes, materials } = useGLTF('models/gltfjsx/CannonLevel-transformed.glb')

  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh geometry={nodes.UpperWallPanels001.geometry} material={nodes.UpperWallPanels001.material} position={[-15.122, 14.427, -35]} />
      <mesh geometry={nodes.SmallRooms001.geometry} material={materials['YellowMetal.001']} position={[-10.194, 0.002, -3.088]} />
      <mesh geometry={nodes.RightWall001.geometry} material={materials['BrownBricks.001']} position={[14.959, -0.01, 0.02]} rotation={[0, 0, -Math.PI / 2]} />
      <group position={[13.597, 4.219, -25.036]} scale={[1.021, 1, 1.302]}>
        <mesh geometry={nodes.Plane014.geometry} material={materials['PaintedMetal.001']} />
        <mesh geometry={nodes.Plane014_1.geometry} material={materials['ConcreteFloor.001']} />
      </group>
      <mesh geometry={nodes.Plane001.geometry} material={materials['DarkGrayMetal.001']} position={[14.959, 5.667, 4.375]} scale={[1, 1, 0.999]} />
      <mesh geometry={nodes.PillarFrames001.geometry} material={materials['RedMetal.001']} position={[-13.622, 11.487, 4.964]} />
      <mesh geometry={nodes.Pillar001.geometry} material={materials['Concrete.001']} position={[-14.999, 0.001, 5.625]} />
      <mesh geometry={nodes.Frame033.geometry} material={materials['BlueMetal.001']} position={[4.328, -0.01, -11.871]} rotation={[0, -1.571, 0]} scale={[1, 1.554, 1]} />
      <mesh geometry={nodes.Cube010.geometry} material={materials['Concrete.001']} />
      <mesh geometry={nodes.ConcreteRect001.geometry} material={materials['Concrete.001']} position={[-0.303, 1.432, -16.464]} />
    </group>
  )
})

useGLTF.preload('models/gltfjsx/CannonLevel-transformed.glb')
