/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 Level02.glb --transform
*/

import React, { forwardRef, useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export const Level02Model = forwardRef((props, weightRef) => {
  const { nodes, materials } = useGLTF('models/gltfjsx/Level02-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group ref={weightRef}>
        <mesh geometry={nodes.Pulley004.geometry} material={materials.BlackMetal} position={[0, 0.355, -2.467]} />
        <mesh geometry={nodes.Rope004.geometry} material={materials.Rope} position={[0, 0.356, -2.518]} />
        <mesh geometry={nodes.Circle003.geometry} material={materials.Rope} position={[0, 0.355, -2.418]} />
        <mesh geometry={nodes.PulleyWeight.geometry} material={materials.Alluminium} position={[0, 0.355, -2.467]} rotation={[0, 0, -Math.PI / 2]} scale={[0.01, 0.032, 0.01]} />
        <mesh geometry={nodes.Weight.geometry} material={materials.AlluminiumDark} position={[0, 0.178, -2.467]} scale={[0.069, 0.089, 0.069]} />
      </group>
      <mesh geometry={nodes.Ring.geometry} material={nodes.Ring.material} position={[0, 0.595, 2.5]} />
      <mesh geometry={nodes.Ground.geometry} material={materials.Ground} />
      <mesh geometry={nodes.Sphere.geometry} material={nodes.Sphere.material} position={[0, 0.6, 2.5]} />
      <mesh geometry={nodes.Rope003.geometry} material={materials.Rope} position={[0, 0.548, -2.416]} rotation={[0, 0, -Math.PI]} />
      <mesh geometry={nodes.Rope001.geometry} material={materials.Rope} position={[0, 0.6, 2.304]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Laser.geometry} material={nodes.Laser.material} position={[0, -4, -2.835]} />
      <mesh geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} position={[0, 0.595, 2.5]} scale={[1.196, 0.598, 1.196]} />
      <mesh geometry={nodes.Bench.geometry} material={materials.Wood} position={[0, 0.35, 0.231]} />
      <mesh geometry={nodes.Foots.geometry} material={materials.Wood} position={[0.155, 0.233, -1.95]} />
      <mesh geometry={nodes.Pulley.geometry} material={materials.BlackMetal} position={[0, 0.348, -2.02]} rotation={[Math.PI / 6, 0, 0]} scale={[0.336, 1, 1]} />
      <mesh geometry={nodes.Pulley001.geometry} material={materials.BlackMetal} position={[0, 0.548, -2.366]} rotation={[Math.PI / 6, 0, 0]} scale={[0.158, 1, 1]} />
      <mesh geometry={nodes.Rope002.geometry} material={materials.Rope} position={[0, 0.6, -2.366]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cabinet.geometry} material={materials.Alluminium} position={[-2.75, 0, 0.463]} />
      <mesh geometry={nodes.CabinetDoor.geometry} material={materials.AlluminiumDark} position={[-2.307, 0, 1.147]} rotation={[-Math.PI, -0.527, -Math.PI]} />
      <mesh geometry={nodes.CabinetDoor001.geometry} material={materials.AlluminiumDark} position={[-2.307, 0, -0.22]} rotation={[-Math.PI, Math.PI / 6, -Math.PI]} />
      <mesh geometry={nodes.Plane.geometry} material={materials.AlluminiumDark} position={[-2.694, 0.4, 0.463]} scale={[0.286, 0.656, 0.656]} />
      <mesh geometry={nodes.Ceiling.geometry} material={materials.Walls} position={[0, 3, -0.5]} rotation={[-Math.PI, 0, 0]} />
      <mesh geometry={nodes.PulleyCeiling.geometry} material={materials.BlackMetal} position={[0, 3, -2.518]} />
      <mesh geometry={nodes.Rope.geometry} material={materials.Rope} position={[0, 2.847, -2.518]} rotation={[0, 0, Math.PI]} />
      <mesh geometry={nodes.Walls.geometry} material={materials.Walls} position={[3, 1, 3]} />
      <mesh geometry={nodes.DoorFrame.geometry} material={materials.WoodWhite} position={[-2.75, 0, -1.963]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Door.geometry} material={materials.Wood} position={[-2.728, 1.05, -2.381]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Handle_Back.geometry} material={materials.Alluminium} position={[-2.733, 1.05, -1.617]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Handle_Front.geometry} material={nodes.Handle_Front.material} position={[-2.757, 1.05, -1.617]} rotation={[Math.PI, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Well.geometry} material={materials.Well} position={[0, -0.01, -2.5]} />
    </group>
  )
})

useGLTF.preload('models/gltfjsx/Level02-transformed.glb')
