/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 Ring.glb --transform --simplyfy
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Ring(props) {
  const { nodes, materials } = useGLTF('models/gltfjsx/Ring-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Circle.geometry} material={nodes.Circle.material} />
    </group>
  )
}
useGLTF.preload('models/gltfjsx/Ring-transformed.glb')