/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 WindowBlueprint.glb --simplify --transform
*/

import React, { forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'

export const WindowBlueprint = forwardRef((props, ref) => {
  const { setSelectedObject, selectedObject } = props
  const { nodes, materials } = useGLTF('models/gltfjsx/WindowBlueprint-transformed.glb')
  return (
    <group name='blueprint' {...props} dispose={null} onPointerDown={(obj) => {
      obj.stopPropagation()
      setSelectedObject(obj.eventObject)
    }
    }>
      <mesh geometry={nodes.WindowBlueprint.geometry} material={materials.WindowBlueprint} position={[13, 7, 5.038]} scale={1} />
    </group>
  )
})

useGLTF.preload('models/gltfjsx/WindowBlueprint-transformed.glb')
